goserver:
  image: gocd/gocd-server:14.4.0
  ports:
    - "8153:8153"
  links:
#    - nexus:nexus
    - gitbucket:git
  volumes:
    - ./ssh/:/var/go/.ssh
    - ./go-server-config:/etc/go
  privileged: true
goagent:
  build: ./go-agent/
#  image: gocd/gocd-agent:14.4.0
  links:
    - goserver:go-server
#    - nexus:nexus
    - gitbucket:git
#  volumes:
#    - ./ssh-agent:/var/go/.ssh
  privileged: true
#nexus:
#  image: sonatype/nexus
#  ports:
#    - "8081:8081"
gitbucket:
  image: f99aq8ove/gitbucket
  ports:
    - "8080:8080"
    - "29418:29418"
#  links:
#    - nexus:nexus
  volumes:
     - ./gitbucket-data:/gitbucket
  privileged: true
