goserver:
  image: gocd/gocd-server:14.4.0
  ports:
    - "8153:8153"
  links:
#    - nexus:nexus
    - gitlab:git
  volumes:
    - ./ssh/:/var/go/.ssh
    - ./go-server-config:/etc/go
  privileged: true
goagent:
  build: ./go-agent/
#  image: gocd/gocd-agent:14.4.0
  links:
    - goserver:go-server
#    - nexus:nexus
    - gitlab:git
#  volumes:
#    - ./ssh-agent:/var/go/.ssh
  privileged: true
nexus:
  image: sonatype/nexus
  ports:
    - "8081:8081"
  volumes:
    - ./nexus-data:/sonatype-work
postgresql:
  image: sameersbn/postgresql:9.4
  environment:
     - DB_USER=gitlab
     - DB_PASS=secretpassword
     - DB_NAME=gitlabhq_production
  volumes:
     - ./postgresql/data:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:7.9.2
  links:
     - redis:redisio
     - postgresql:postgresql
  ports:
     - "10080:80"
     - "10022:22"
redis:
  image: sameersbn/redis:latest
  privileged: true
